withoutPing
Ksilen/WeatherWidget pull request #3
Opened 2022-02-11 11:15 UTC by Ksilen

2022-02-11 12:56 UTC, matreshkin commented
Осталось поле ввода в окне
![Screenshot from 2022-02-11 15-55-21](https://user-images.githubusercontent.com/5363053/153595136-b0eb657c-0b0b-4ec5-87e0-b7c506d55eae.png)

2022-02-11 12:57 UTC, matreshkin commented
Я не понял, зачем вводить apikey человеку? Если просто в учебных целях, то ок.
А вообще, apikey - выдается на конкретное приложение обычно.

2022-02-11 13:05 UTC, matreshkin commented
Больше не делай отдельных ПР для правок.

Если хочешь "сохранить" какое-то состояние кода, и не будешь его развивать то делай `git tag` на текущем коммите - это специально сделано для этого, чтобы легко найти коммит по имени тега.

Если ты планируешь работать над этой версией, то тогда создавай вторую ветку, но правки делать именно в ветке для ПР, а вторую ветку разрабатывать локально.

2022-02-11 13:07 UTC, matreshkin requested changes

2022-02-11 13:07 UTC, matreshkin commented on database.h
> +    QTimer* timer2 = new QTimer(this); //таймер для пинга, когда сети нет
Это кажется не нужно уже

2022-02-11 13:07 UTC, matreshkin commented on database.h
> +    QTimer timerOne; //таймер для запросов,когда есть сеть
А это нужно?

2022-02-11 13:07 UTC, matreshkin commented on widgetforapikey.h
> +    QPushButton* keyOk;
Это можно в поле не хранить, как я понял

2022-02-11 13:07 UTC, matreshkin commented on widgetforapikey.h
> +    virtual ~WidgetForApiKey();
сейчас часто пишут (и для методов, и для деструкторов)
`~WidgetForApiKey() override; `
вместо
`virtual ~WidgetForApiKey();`

Для методов это очевидно (см. ниже), для деструкторов это смысла не имеет (afaik) и делают просто, чтобы делать везде одинаково.

По слову override компилятор может проверить, что ты действительно переопределяешь метод. Например, если базовый метод поменяет название, а ты у наследника не поменяешь, то компилятор ругнется. Если у тебя только virtual, то эта ошибка пройдет незамеченной.

2022-02-11 13:07 UTC, matreshkin commented on widgetforapikey.h
> +#include <QWidget>
пустая строка пропала

2022-02-11 13:07 UTC, matreshkin commented on widgetforapikey.h
> +#define WIDGETFORAPIKEY_H
пустая строка пропала

2022-02-11 13:07 UTC, matreshkin commented on widget.cpp
> +    windowForApiKey = new WidgetForApiKey;
А чего ты его диалогом не сделаешь?
https://doc.qt.io/qt-5/qdialog.html

2022-02-11 13:07 UTC, matreshkin commented on widget.cpp
> +    case QSystemTrayIcon::Trigger:
Помоему, тут должен быть отступ (не уверен)

2022-02-11 13:07 UTC, matreshkin commented on widget.cpp
> +    case QSystemTrayIcon::Trigger:
Так как это внутри блока

2022-02-11 13:07 UTC, matreshkin commented on database.h
> +    QString apiKey = "749d4862b2ad4bd9fdcada0252405c3e"; //ключ для запросов к OpenWeather(можно ввести другой и он запишется в БД)
Константы сейчас модно делать через unnamed namespace в cpp модуле

2022-02-11 13:07 UTC, matreshkin commented on database.h
> +    void absTemperature(int& intCurTemp, double& curTemp); //если t = 22.6 сделать 23
Пустую строку

2022-02-13 20:45 UTC, Ksilen commented
ой

2022-02-13 20:48 UTC, Yskaj commented
ой

2022-02-26 06:47 UTC, merged